# config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # ...

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
#            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: check
                default_target_path: app_check_ok
            logout:
                path: logout
                target: /form/select
